version: "2"

services:
    nginx-proxy:
        image: nginx:stable
        restart: unless-stopped
        volumes:
            - ./nginx-proxy/conf:/etc/nginx/conf.d:ro
            - ./nginx-proxy/certs:/etc/nginx/certs:ro
            - ./certbot/conf:/etc/letsencrypt:ro
            - ./certbot/www:/var/www/certbot:ro
        ports:
            - "8443:443"
            - "8080:80"
        depends_on:
            - nextcloud

    certbot:
        image: certbot/certbot:latest
        restart: "no"
        depends_on:
            - nginx-proxy
        volumes: 
            - ./certbot/conf:/etc/letsencrypt:rw
            - ./certbot/www:/var/www/certbot:rw
        command: certonly -v --webroot -w /var/www/certbot --force-renewal --email dubtsov@gmail.com -d cloud.dubtsov.net -d www.dubtsov.net -d dubtsov.net --agree-tos

    db:
        image: mariadb:11.0
        restart: unless-stopped
        volumes:
            - ./db/db:/var/lib/mysql
            - ./db/mariadb.conf.d:/etc/mysql/mariadb.conf.d
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    redis:
        image: redis:latest
        restart: unless-stopped

    nextcloud:
        image: nextcloud:latest
        restart: unless-stopped
        volumes:
            - ./nextcloud/config:/var/www/html/config
            - ./nextcloud/data:/var/www/html/data
        depends_on:
            - redis
            - db

    nextcloud-webcron:
        image: cw1900/docker-webcron:latest
        restart: unless-stopped
        environment:
            - INTERVAL_TIME=900
            - URL=-k https://cloud.dubtsov.net/cron.php
        depends_on:
            - nextcloud

# vim:ft=yaml autoindent ts=4 sw=4 et
