version: "2"

services:
    ssl:
        image: nginx:stable
        restart: unless-stopped
        volumes:
            - ./ssl:/etc/nginx/conf.d:ro
        ports:
            - "8443:443"

    db:
        image: mariadb
        restart: unless-stopped
        volumes:
            - ./db/db:/var/lib/mysql
            - ./db/mariadb.conf.d:/etc/mysql/mariadb.conf.d
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}

    redis:
        image: redis
        restart: unless-stopped

    nextcloud:
        image: nextcloud:latest
        restart: unless-stopped
        volumes:
            - ./nextcloud/config:/var/www/html/config
            - ./nextcloud/data:/var/www/html/data
        depends_on:
            - redis
            - db

    nextcloud-webcron:
        image: cw1900/docker-webcron:latest
        restart: unless-stopped
        environment:
            - INTERVAL_TIME=900
            - URL=-k https://cloud.dubtsov.net/cron.php
        depends_on:
            - nextcloud

# vim:ft=yaml autoindent ts=4 sw=4 et
